"""empty message

Revision ID: 2946bfaf61b6
Revises: 74c39d30db92
Create Date: 2021-06-27 09:56:52.365170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2946bfaf61b6'
down_revision = '74c39d30db92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('r_name', sa.String(length=200), nullable=False))
    op.drop_column('room', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('name', sa.VARCHAR(length=120), nullable=False))
    op.drop_column('room', 'r_name')
    # ### end Alembic commands ###
