"""empty message

Revision ID: 2af6ec074829
Revises: 2946bfaf61b6
Create Date: 2021-06-27 15:59:23.828632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af6ec074829'
down_revision = '2946bfaf61b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('DateTime', sa.TIMESTAMP(), nullable=False))
    op.drop_column('room', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.drop_column('room', 'DateTime')
    # ### end Alembic commands ###
