"""empty message

Revision ID: 492651849713
Revises: ec68dcd0974b
Create Date: 2021-07-01 12:37:31.230352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492651849713'
down_revision = 'ec68dcd0974b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('Rid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Rid'], ['room.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_member')
    # ### end Alembic commands ###
