"""empty message

Revision ID: 60f85290b053
Revises: 80f83f24060c
Create Date: 2021-06-28 10:02:58.398849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f85290b053'
down_revision = '80f83f24060c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('created_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
