"""empty message

Revision ID: 80f83f24060c
Revises: 2af6ec074829
Create Date: 2021-06-27 16:02:40.626034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f83f24060c'
down_revision = '2af6ec074829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('room', 'DateTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('DateTime', sa.TIMESTAMP(), nullable=False))
    op.drop_column('room', 'created_at')
    # ### end Alembic commands ###
